### ISSUE TITLE
Possible licence incompatibility

### ISSUE THREAD

**Issue by kuzkry** [muttleyxd/clang-format-static-binaries#3]
Nice work!

I'm not really a lawyer but you may wanna investigate if your current [_Unlicence_](https://github.com/muttleyxd/clang-format-static-binaries/blob/52c3f9e726c360bac9692c7645f15716126dea4a/LICENSE) matches pre-clang9 [_University of Illinois/NCSA License_](https://github.com/llvm/llvm-project/blob/7c9c5362efa4c0dedc9de19ac76640fa89838b4a/clang/LICENSE.TXT) and latest [_Apache License 2.0 with LLVM Exceptions_](https://github.com/llvm/llvm-project/blob/4a1b95bda0c444798a5240fe924dd127b776d12d/clang/LICENSE.TXT) effective from clang9.

I think you need to provide some missing copyright notices and relicense it, especially now before this repository gets popular.

**Comment by muttleyxd** [comment]
Added licenses both to release and AUR package, thanks for reporting!
